name: jenkins_p2g_swbundle
channels:
  - conda-forge
dependencies:
  - aggdraw
  - appdirs
  - cftime
  - conda-pack
  - configobj
  - curl
  - dask>=2022.6.1
  - distributed>=2022.6.1
  - donfig
  - ffmpeg
  - fontconfig
  - freetype
  - gdal
  - h5py
  - netcdf4
  - pillow
  - pip
  - pooch
  - pycoast>=1.6.0
  - pydecorate>=0.3.3
  - pyhdf
  - pykdtree
  - pyorbital>=1.7.2
  - pyproj>=3.1.0
  - pyresample>=1.25.0
  - pyshp
  - pyspectral>=0.12.2
  - python=3.10
  - python-geotiepoints>=1.5.0
  - pyyaml
  - rasterio>=1.2.10
  - requests
  - setuptools
  - six
  - trollimage>=1.19.0
  - trollsift>=0.4.0
  - scipy
  - zarr
  - xarray>=2022.3.0
  - fsspec
  - s3fs
  - pip:
    - git+https://github.com/pytroll/satpy.git
