name: Deploy sdist

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create sdist
        shell: bash -l {0}
        run: python setup.py sdist

      - name: Publish package to PyPI
        # upload to PyPI on every release for a tag starting with 'v'
        if: github.event.action == 'published' && startsWith(github.event.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.6.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
